snowflake_dbt:
  target: dev

  outputs:

    dev:
      type: snowflake
      role: DBT_DEV_ROLE
      warehouse: COMPUTE_WH
      database: AIRBNB
      schema: ANALYTICS
      threads: 8

    prod:
      type: snowflake
      role: DBT_PROD_ROLE
      warehouse: COMPUTE_WH
      database: AIRBNB
      schema: ANALYTICS_PROD
      threads: 8